server:
  port: 8080

spring:
  redis:
    port: 6379
    host: localhost
    database: 0       #数据库索引
    pool:
      min-idle: 0     #最小空闲链接
      max-active: 8   #最大连接数
      max-idle: 8     #最大空闲链接
      max-wait: -1    #最大阻塞时间 （-1 没有限制）
    timeout: 0        #连接超时时间